spring:
  datasource:
    url: jdbc:postgresql://flammedb.chykkgmuq4ca.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: MarinaRabelo!1995
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

server:
  port: 5432